[[constraint]]
  name = "github.com/slok/kubewebhook"
  version = "0.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[prune]
  go-tests = true
  unused-packages = true
